/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.rerorero.kafka.connect.transform.encrypt;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
